/*
389. Find the Difference
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
#include <iostream>
#include <string>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <cmath>
#include <queue>
#include <stack>
#include <stdio.h>
#include <map>
#include <numeric>
using namespace std;

class Solution {
public:
    char findTheDifference(string s, string t) {
        vector<int> letters(26, 0);
        for (int i = 0; i < s.size(); i++) {
            letters[s[i] - 'a'] += 1;
        }

        int i = 0;
        for (; i < t.size(); i++) {
            letters[t[i] - 'a'] -= 1;
            if (letters[t[i] - 'a'] < 0) {
                break;
            }
        }
        return t[i];
    }
};
